### ISSUE TITLE
The evaluation results i get are lower than reported in the paper

### ISSUE THREAD

**Issue by yukaroman** [ictnlp/DSTC8-AVSD#3]
Hi, Thank you for sharing the code, but i have a little problem when reproducing the evaluation results like `BLEU-1`, `BLEU-2`, `BLEU-3`, `METEOR`. I use exactly the same code as you produced, and the generate result seems good. But when I use the evaluation tools produced in DSTC7-AVSD CHALLENGE or DSTC8-AVSD CHALLENGE, I only get `Bleu_1: 0.687`, `Bleu_2: 0.562`, `CIDEr: 1.034`, which are lower than the result in the paper(like `Bleu_1: 0.759`). Can you help me solve this problem or provide some pretrained model? Thanks.

**Comment by lizekang** [comment]
Thanks for your attention to our paper. There is a little bug in the code. I have fixed it just now. The problem was that the drop_caption flag was True not while training but while generating sentences. So I changed the drop_caption flag to False at line 102 in generate.py.

**Comment by yukaroman** [comment]
Thanks for your quick reply and I will test again.
